### ISSUE TITLE
sObject Dependency Injection

### ISSUE THREAD

**Issue by torynet** [afawcett/force-di#28]
Hello gentlemen. First of all, thanks for all your hard work. This is awesome.

I have a DI use case where I would like to inject an sObject based on the type of another sObject. So, for example, I have a lightning component that "hasRecordId" and it would like determine the sObject type of that record Id and pass that information along and get another related sObject in return, without having to have any knowledge of it, except that it can expect to get back an sObject that meets certain requirements. The idea here is to make the lightning component be versatile and capable of working with new sObjects based purely on the addition of an appropriate sObject and a CMDT entry that links them.

Essentially this is sObject dependency injection. So, I can for example, have the package work with Accounts and have a related object for it that has the fields etc my component is expecting to work with. Then, if I decide to install CPQ, now maybe I need a new similar sObject that does the same thing, but is linked to SBQQ__Quote__c instead of Account. In my case I am using these sObjects as many to many linking objects between an sObject in the package and other sObjects. I would like it to be dynamic and be able to add support for additional sObjects based simply upon adding a new linking object and a CMDT entry. This lets me still have working Salesforce reporting and I can work with any sObject without having to make any changes to my package and it's classes and components.

I know I can do this by just adding my own CMDT, but I am already using Force DI and it seems like a natural extension of Force DI. So, I was thinking I could simply add another field to the Force DI CMDT such as "Bound Object", and add some appropriate methods to Force DI. That way if I'm trying to bind an sObject, it's just a matter of filling out that field. You would simply leave it empty just as you do the "Binding Object" field, if you didn't need it. This way sObjects could be bound dynamically in all the same ways that Classes are. You don't have interfaces for sObjects, so the user is responsible for making sure the sObject will fit the requirements or it will cause errors, but that is unavoidable.

So, my question is, do you see any reason that this is not a good fit or that I should just make a different CMDT and not involve Force DI?

Thanks for your time,

Tory Netherton

**Comment by torynet** [comment]
Also, I do realize that this could be accomplished by simply adding another "type", putting the SObject name into the "to" field and adding another binding class, but it seems like a shame to lose the "type checking" inherent in having the CMDT reference the actual SObject type rather than just typing in a string. Unless it would be significantly disruptive, it seems better to use a separate field. You need additional methods as well to return the SObjectType rather than an instance. Obviously I'm still trying to think through the nuances.

**Comment by ImJohnMDaniel** [comment]
G'day @torynet -- thanks for reaching out.

I agree with @douglascayers that it may not be a good fit to adapt the standard Binding__mdt with a new "Bound Object" field.  I say that because I don't see many use cases for this extra field outside of what you are asking for.

I would suggest using your own CMDT and then load it up in Force-DI via the "module" route.  I am currently doing that on 6 different use cases where they have very specific requirements for the data on the CMDT object so I have 6 different modules that I am loading.  

If you want to return an SObjectType and not an instantiated class, then you probably have to setup your own Provider class to manage it verses using the default implementation to instantiate classes.  I think this should be a workable approach for you.  In that case, you would setup a Binding__mdt record with a module type that would bind to an instance that implements `di_Binding.Provider`.  That way you could return whatever SObject that you want to.

Let me know if you have any questions here.

Hope this helps.  Cheers!

**Comment by torynet** [comment]
Excellent. Thank you both for your insights. I will adopt the strategy John has suggested and see how it goes.

I really appreciate you both taking the time.

**Comment by torynet** [comment]
@ImJohnMDaniel One more related question. So many things need injected. Are you using Force DI to inject field sets? If so, are you just using a similar strategy of creating your own cmdt and provider?

**Comment by ImJohnMDaniel** [comment]
@torynet -- Precisely that.

**Comment by torynet** [comment]
And I suppose it's the same thing for domain and selector objects that need constructor parameters. So, clearly we're going to have a lot of our own providers. Thanks for all the assistance John. It's really helpful.

**Comment by ImJohnMDaniel** [comment]
Basically yes.  I sent you some examples via LinkedIn.  Take a look at let me know if you have questions.
